Update GitHub.yaml
Removing brackets in both echo commands as this causes a syntax error in github.com actions:

/home/runner/work/_temp/28b6cf36-53f1-44d2-82da-3aecee89d37d.sh: line 3: syntax error near unexpected token `('
Error: Process completed with exit code 2.